import type { LucideProps } from "lucide-react"
import {
  AlertCircle,
  Award,
  BookOpen,
  Boxes,
  Briefcase,
  Building,
  Building2,
  Calendar,
  CheckCircle2,
  CheckSquare,
  CircleDot,
  Clock,
  Database,
  Eye,
  FileCheck,
  FileSearch,
  FileSpreadsheet,
  FileText,
  Files,
  Filter,
  Folder,
  FolderOpen,
  FolderTree,
  Grid,
  Hash,
  HelpCircle,
  Key,
  Layers,
  LayoutDashboard,
  LayoutGrid,
  List,
  ListFilter,
  ListOrdered,
  ListTodo,
  Lock,
  Mail,
  MapPin,
  Menu as MenuIcon,
  Package,
  PackageCheck,
  Paperclip,
  QrCode,
  RotateCcw,
  Ruler,
  ScrollText,
  Search,
  Server,
  Settings,
  Settings2,
  Share2,
  Shield,
  ShieldAlert,
  ShieldCheck,
  SlidersHorizontal,
  Tag,
  Tags,
  Trash2,
  Truck,
  Type,
  UserCheck,
  UserCog,
  Users,
  Wrench,
} from "lucide-react"

export const AVAILABLE_MENU_ICONS = [
  { name: "layout-dashboard", label: "Dashboard / Inicio", icon: LayoutDashboard },
  { name: "shield", label: "Seguridad", icon: Shield },
  { name: "shield-check", label: "Permisos / Aprobación", icon: ShieldCheck },
  { name: "users", label: "Usuarios / Personas", icon: Users },
  { name: "user-check", label: "Empleados", icon: UserCheck },
  { name: "user-cog", label: "Configuración Usuario", icon: UserCog },
  { name: "key", label: "Claves / Acceso", icon: Key },
  { name: "lock", label: "Bloqueo", icon: Lock },
  { name: "building-2", label: "Organización", icon: Building2 },
  { name: "building", label: "Áreas / Edificios", icon: Building },
  { name: "briefcase", label: "Cargos", icon: Briefcase },
  { name: "award", label: "Responsabilidades", icon: Award },
  { name: "boxes", label: "Activos / Cajas", icon: Boxes },
  { name: "package", label: "Insumos / Paquetes", icon: Package },
  { name: "package-check", label: "Inventario Revisado", icon: PackageCheck },
  { name: "layout-grid", label: "Catálogo", icon: LayoutGrid },
  { name: "folder-tree", label: "Jerarquía / Árbol", icon: FolderTree },
  { name: "folder", label: "Carpeta", icon: Folder },
  { name: "folder-open", label: "Carpeta Abierta", icon: FolderOpen },
  { name: "tags", label: "Etiquetas / Tipos", icon: Tags },
  { name: "tag", label: "Etiqueta", icon: Tag },
  { name: "paperclip", label: "Accesorios", icon: Paperclip },
  { name: "file-text", label: "Documentos / Informes", icon: FileText },
  { name: "file-search", label: "Consulta Documentos", icon: FileSearch },
  { name: "file-check", label: "Auditorías", icon: FileCheck },
  { name: "file-spreadsheet", label: "Hojas de Cálculo", icon: FileSpreadsheet },
  { name: "files", label: "Archivos Múltiples", icon: Files },
  { name: "settings-2", label: "Parámetros", icon: Settings2 },
  { name: "settings", label: "Ajustes", icon: Settings },
  { name: "sliders-horizontal", label: "Gestión", icon: SlidersHorizontal },
  { name: "book-open", label: "Catálogos / Guías", icon: BookOpen },
  { name: "map-pin", label: "Ubicaciones", icon: MapPin },
  { name: "type", label: "Tipos de Datos", icon: Type },
  { name: "ruler", label: "Unidades de Medida", icon: Ruler },
  { name: "wrench", label: "Mantenimientos", icon: Wrench },
  { name: "list-todo", label: "Actividades", icon: ListTodo },
  { name: "check-square", label: "Checklists", icon: CheckSquare },
  { name: "alert-circle", label: "Prioridades / Alertas", icon: AlertCircle },
  { name: "scroll-text", label: "Logs de Migración", icon: ScrollText },
  { name: "list", label: "Lista", icon: List },
  { name: "list-filter", label: "Filtros", icon: ListFilter },
  { name: "list-ordered", label: "Orden", icon: ListOrdered },
  { name: "layers", label: "Módulos / Capas", icon: Layers },
  { name: "database", label: "Base de Datos", icon: Database },
  { name: "server", label: "Servidor", icon: Server },
  { name: "truck", label: "Transporte", icon: Truck },
  { name: "qr-code", label: "Código QR", icon: QrCode },
  { name: "menu", label: "Menú", icon: MenuIcon },
] as const

const ICONS_MAP: Record<string, React.ComponentType<LucideProps>> = {
  "alert-circle": AlertCircle,
  award: Award,
  "book-open": BookOpen,
  boxes: Boxes,
  briefcase: Briefcase,
  building: Building,
  "building-2": Building2,
  calendar: Calendar,
  "check-circle-2": CheckCircle2,
  "check-square": CheckSquare,
  "circle-dot": CircleDot,
  clock: Clock,
  database: Database,
  eye: Eye,
  "file-check": FileCheck,
  "file-search": FileSearch,
  "file-spreadsheet": FileSpreadsheet,
  "file-text": FileText,
  files: Files,
  filter: Filter,
  folder: Folder,
  "folder-open": FolderOpen,
  "folder-tree": FolderTree,
  grid: Grid,
  hash: Hash,
  "help-circle": HelpCircle,
  key: Key,
  layers: Layers,
  "layout-dashboard": LayoutDashboard,
  "layout-grid": LayoutGrid,
  list: List,
  "list-filter": ListFilter,
  "list-ordered": ListOrdered,
  "list-todo": ListTodo,
  lock: Lock,
  mail: Mail,
  "map-pin": MapPin,
  menu: MenuIcon,
  package: Package,
  "package-check": PackageCheck,
  paperclip: Paperclip,
  "qr-code": QrCode,
  "rotate-ccw": RotateCcw,
  ruler: Ruler,
  "scroll-text": ScrollText,
  search: Search,
  server: Server,
  settings: Settings,
  "settings-2": Settings2,
  "share-2": Share2,
  shield: Shield,
  "shield-alert": ShieldAlert,
  "shield-check": ShieldCheck,
  "sliders-horizontal": SlidersHorizontal,
  tag: Tag,
  tags: Tags,
  "trash-2": Trash2,
  truck: Truck,
  type: Type,
  "user-check": UserCheck,
  "user-cog": UserCog,
  users: Users,
  wrench: Wrench,
}

type DynamicLucideIconProps = LucideProps & {
  name?: string | null
  fallback?: React.ComponentType<LucideProps>
}

export function DynamicLucideIcon({
  name,
  fallback = Folder,
  ...props
}: DynamicLucideIconProps) {
  if (!name) {
    const FallbackIcon = fallback
    return <FallbackIcon {...props} />
  }

  const normalized = name.toLowerCase().trim()
  const IconComponent = ICONS_MAP[normalized]

  if (!IconComponent) {
    const FallbackIcon = fallback
    return <FallbackIcon {...props} />
  }

  return <IconComponent {...props} />
}
