/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../../routes/__root'
import { Route as DashboardRouteImport } from './../../routes/_dashboard'
import { Route as LoginRouteImport } from './../../routes/login'
import { Route as DashboardIndexRouteImport } from './../../routes/_dashboard/index'
import { Route as DashboardActivosRouteImport } from './../../routes/_dashboard/activos'
import { Route as DashboardParametrosRouteRouteImport } from './../../routes/_dashboard/parametros/route'
import { Route as DashboardPerfilRouteImport } from './../../routes/_dashboard/perfil'
import { Route as DashboardTiposActivoRouteRouteImport } from './../../routes/_dashboard/tipos-activo/route'
import { Route as DashboardParametrosCatalogosRouteImport } from './../../routes/_dashboard/parametros/catalogos'
import { Route as DashboardParametrosGestionRouteImport } from './../../routes/_dashboard/parametros/gestion'
import { Route as DashboardParametrosTiposDatoRouteImport } from './../../routes/_dashboard/parametros/tipos-dato'
import { Route as DashboardTiposActivoIndexRouteImport } from './../../routes/_dashboard/tipos-activo/index'
import { Route as DashboardTiposActivoAtributosRouteImport } from './../../routes/_dashboard/tipos-activo/atributos'
import { Route as DashboardTiposActivoHistorialRouteImport } from './../../routes/_dashboard/tipos-activo/historial'

const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardActivosRoute = DashboardActivosRouteImport.update({
  id: '/activos',
  path: '/activos',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardParametrosRouteRoute =
  DashboardParametrosRouteRouteImport.update({
    id: '/parametros',
    path: '/parametros',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPerfilRoute = DashboardPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTiposActivoRouteRoute =
  DashboardTiposActivoRouteRouteImport.update({
    id: '/tipos-activo',
    path: '/tipos-activo',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardParametrosCatalogosRoute =
  DashboardParametrosCatalogosRouteImport.update({
    id: '/catalogos',
    path: '/catalogos',
    getParentRoute: () => DashboardParametrosRouteRoute,
  } as any)
const DashboardParametrosGestionRoute =
  DashboardParametrosGestionRouteImport.update({
    id: '/gestion',
    path: '/gestion',
    getParentRoute: () => DashboardParametrosRouteRoute,
  } as any)
const DashboardParametrosTiposDatoRoute =
  DashboardParametrosTiposDatoRouteImport.update({
    id: '/tipos-dato',
    path: '/tipos-dato',
    getParentRoute: () => DashboardParametrosRouteRoute,
  } as any)
const DashboardTiposActivoIndexRoute =
  DashboardTiposActivoIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardTiposActivoRouteRoute,
  } as any)
const DashboardTiposActivoAtributosRoute =
  DashboardTiposActivoAtributosRouteImport.update({
    id: '/atributos',
    path: '/atributos',
    getParentRoute: () => DashboardTiposActivoRouteRoute,
  } as any)
const DashboardTiposActivoHistorialRoute =
  DashboardTiposActivoHistorialRouteImport.update({
    id: '/historial',
    path: '/historial',
    getParentRoute: () => DashboardTiposActivoRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/login': typeof LoginRoute
  '/parametros': typeof DashboardParametrosRouteRouteWithChildren
  '/tipos-activo': typeof DashboardTiposActivoRouteRouteWithChildren
  '/activos': typeof DashboardActivosRoute
  '/perfil': typeof DashboardPerfilRoute
  '/parametros/catalogos': typeof DashboardParametrosCatalogosRoute
  '/parametros/gestion': typeof DashboardParametrosGestionRoute
  '/parametros/tipos-dato': typeof DashboardParametrosTiposDatoRoute
  '/tipos-activo/atributos': typeof DashboardTiposActivoAtributosRoute
  '/tipos-activo/historial': typeof DashboardTiposActivoHistorialRoute
  '/tipos-activo/': typeof DashboardTiposActivoIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/parametros': typeof DashboardParametrosRouteRouteWithChildren
  '/activos': typeof DashboardActivosRoute
  '/perfil': typeof DashboardPerfilRoute
  '/': typeof DashboardIndexRoute
  '/parametros/catalogos': typeof DashboardParametrosCatalogosRoute
  '/parametros/gestion': typeof DashboardParametrosGestionRoute
  '/parametros/tipos-dato': typeof DashboardParametrosTiposDatoRoute
  '/tipos-activo/atributos': typeof DashboardTiposActivoAtributosRoute
  '/tipos-activo/historial': typeof DashboardTiposActivoHistorialRoute
  '/tipos-activo': typeof DashboardTiposActivoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/_dashboard/parametros': typeof DashboardParametrosRouteRouteWithChildren
  '/_dashboard/tipos-activo': typeof DashboardTiposActivoRouteRouteWithChildren
  '/_dashboard/activos': typeof DashboardActivosRoute
  '/_dashboard/perfil': typeof DashboardPerfilRoute
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/parametros/catalogos': typeof DashboardParametrosCatalogosRoute
  '/_dashboard/parametros/gestion': typeof DashboardParametrosGestionRoute
  '/_dashboard/parametros/tipos-dato': typeof DashboardParametrosTiposDatoRoute
  '/_dashboard/tipos-activo/atributos': typeof DashboardTiposActivoAtributosRoute
  '/_dashboard/tipos-activo/historial': typeof DashboardTiposActivoHistorialRoute
  '/_dashboard/tipos-activo/': typeof DashboardTiposActivoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/parametros'
    | '/tipos-activo'
    | '/activos'
    | '/perfil'
    | '/parametros/catalogos'
    | '/parametros/gestion'
    | '/parametros/tipos-dato'
    | '/tipos-activo/atributos'
    | '/tipos-activo/historial'
    | '/tipos-activo/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/parametros'
    | '/activos'
    | '/perfil'
    | '/'
    | '/parametros/catalogos'
    | '/parametros/gestion'
    | '/parametros/tipos-dato'
    | '/tipos-activo/atributos'
    | '/tipos-activo/historial'
    | '/tipos-activo'
  id:
    | '__root__'
    | '/_dashboard'
    | '/login'
    | '/_dashboard/parametros'
    | '/_dashboard/tipos-activo'
    | '/_dashboard/activos'
    | '/_dashboard/perfil'
    | '/_dashboard/'
    | '/_dashboard/parametros/catalogos'
    | '/_dashboard/parametros/gestion'
    | '/_dashboard/parametros/tipos-dato'
    | '/_dashboard/tipos-activo/atributos'
    | '/_dashboard/tipos-activo/historial'
    | '/_dashboard/tipos-activo/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/activos': {
      id: '/_dashboard/activos'
      path: '/activos'
      fullPath: '/activos'
      preLoaderRoute: typeof DashboardActivosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/parametros': {
      id: '/_dashboard/parametros'
      path: '/parametros'
      fullPath: '/parametros'
      preLoaderRoute: typeof DashboardParametrosRouteRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/perfil': {
      id: '/_dashboard/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof DashboardPerfilRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/tipos-activo': {
      id: '/_dashboard/tipos-activo'
      path: '/tipos-activo'
      fullPath: '/tipos-activo'
      preLoaderRoute: typeof DashboardTiposActivoRouteRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/parametros/catalogos': {
      id: '/_dashboard/parametros/catalogos'
      path: '/catalogos'
      fullPath: '/parametros/catalogos'
      preLoaderRoute: typeof DashboardParametrosCatalogosRouteImport
      parentRoute: typeof DashboardParametrosRouteRoute
    }
    '/_dashboard/parametros/gestion': {
      id: '/_dashboard/parametros/gestion'
      path: '/gestion'
      fullPath: '/parametros/gestion'
      preLoaderRoute: typeof DashboardParametrosGestionRouteImport
      parentRoute: typeof DashboardParametrosRouteRoute
    }
    '/_dashboard/parametros/tipos-dato': {
      id: '/_dashboard/parametros/tipos-dato'
      path: '/tipos-dato'
      fullPath: '/parametros/tipos-dato'
      preLoaderRoute: typeof DashboardParametrosTiposDatoRouteImport
      parentRoute: typeof DashboardParametrosRouteRoute
    }
    '/_dashboard/tipos-activo/': {
      id: '/_dashboard/tipos-activo/'
      path: '/'
      fullPath: '/tipos-activo/'
      preLoaderRoute: typeof DashboardTiposActivoIndexRouteImport
      parentRoute: typeof DashboardTiposActivoRouteRoute
    }
    '/_dashboard/tipos-activo/atributos': {
      id: '/_dashboard/tipos-activo/atributos'
      path: '/atributos'
      fullPath: '/tipos-activo/atributos'
      preLoaderRoute: typeof DashboardTiposActivoAtributosRouteImport
      parentRoute: typeof DashboardTiposActivoRouteRoute
    }
    '/_dashboard/tipos-activo/historial': {
      id: '/_dashboard/tipos-activo/historial'
      path: '/historial'
      fullPath: '/tipos-activo/historial'
      preLoaderRoute: typeof DashboardTiposActivoHistorialRouteImport
      parentRoute: typeof DashboardTiposActivoRouteRoute
    }
  }
}

interface DashboardParametrosRouteRouteChildren {
  DashboardParametrosCatalogosRoute: typeof DashboardParametrosCatalogosRoute
  DashboardParametrosGestionRoute: typeof DashboardParametrosGestionRoute
  DashboardParametrosTiposDatoRoute: typeof DashboardParametrosTiposDatoRoute
}

const DashboardParametrosRouteRouteChildren: DashboardParametrosRouteRouteChildren =
  {
    DashboardParametrosCatalogosRoute: DashboardParametrosCatalogosRoute,
    DashboardParametrosGestionRoute: DashboardParametrosGestionRoute,
    DashboardParametrosTiposDatoRoute: DashboardParametrosTiposDatoRoute,
  }

const DashboardParametrosRouteRouteWithChildren =
  DashboardParametrosRouteRoute._addFileChildren(
    DashboardParametrosRouteRouteChildren,
  )

interface DashboardTiposActivoRouteRouteChildren {
  DashboardTiposActivoAtributosRoute: typeof DashboardTiposActivoAtributosRoute
  DashboardTiposActivoHistorialRoute: typeof DashboardTiposActivoHistorialRoute
  DashboardTiposActivoIndexRoute: typeof DashboardTiposActivoIndexRoute
}

const DashboardTiposActivoRouteRouteChildren: DashboardTiposActivoRouteRouteChildren =
  {
    DashboardTiposActivoAtributosRoute: DashboardTiposActivoAtributosRoute,
    DashboardTiposActivoHistorialRoute: DashboardTiposActivoHistorialRoute,
    DashboardTiposActivoIndexRoute: DashboardTiposActivoIndexRoute,
  }

const DashboardTiposActivoRouteRouteWithChildren =
  DashboardTiposActivoRouteRoute._addFileChildren(
    DashboardTiposActivoRouteRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardParametrosRouteRoute: typeof DashboardParametrosRouteRouteWithChildren
  DashboardTiposActivoRouteRoute: typeof DashboardTiposActivoRouteRouteWithChildren
  DashboardActivosRoute: typeof DashboardActivosRoute
  DashboardPerfilRoute: typeof DashboardPerfilRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardParametrosRouteRoute: DashboardParametrosRouteRouteWithChildren,
  DashboardTiposActivoRouteRoute: DashboardTiposActivoRouteRouteWithChildren,
  DashboardActivosRoute: DashboardActivosRoute,
  DashboardPerfilRoute: DashboardPerfilRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
