/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../../routes/__root'
import { Route as DashboardRouteImport } from './../../routes/_dashboard'
import { Route as LoginRouteImport } from './../../routes/login'
import { Route as DashboardIndexRouteImport } from './../../routes/_dashboard/index'
import { Route as DashboardAccesoriosRouteRouteImport } from './../../routes/_dashboard/accesorios/route'
import { Route as DashboardActivosRouteRouteImport } from './../../routes/_dashboard/activos/route'
import { Route as DashboardCategoriasRouteRouteImport } from './../../routes/_dashboard/categorias/route'
import { Route as DashboardInventariosRouteRouteImport } from './../../routes/_dashboard/inventarios/route'
import { Route as DashboardMantenimientosRouteRouteImport } from './../../routes/_dashboard/mantenimientos/route'
import { Route as DashboardOrganizacionRouteRouteImport } from './../../routes/_dashboard/organizacion/route'
import { Route as DashboardParametrosRouteRouteImport } from './../../routes/_dashboard/parametros/route'
import { Route as DashboardPerfilRouteImport } from './../../routes/_dashboard/perfil'
import { Route as DashboardTiposActivoRouteRouteImport } from './../../routes/_dashboard/tipos-activo/route'
import { Route as DashboardTiposDocumentoRouteRouteImport } from './../../routes/_dashboard/tipos-documento/route'
import { Route as DashboardAccesoriosIndexRouteImport } from './../../routes/_dashboard/accesorios/index'
import { Route as DashboardActivosIndexRouteImport } from './../../routes/_dashboard/activos/index'
import { Route as DashboardActivosConsultaDocumentosRouteImport } from './../../routes/_dashboard/activos/consulta-documentos'
import { Route as DashboardActivosNuevoRouteImport } from './../../routes/_dashboard/activos/nuevo'
import { Route as DashboardCategoriasIndexRouteImport } from './../../routes/_dashboard/categorias/index'
import { Route as DashboardInventariosIndexRouteImport } from './../../routes/_dashboard/inventarios/index'
import { Route as DashboardInventariosCategoriasRouteRouteImport } from './../../routes/_dashboard/inventarios/categorias/route'
import { Route as DashboardInventariosNuevoRouteImport } from './../../routes/_dashboard/inventarios/nuevo'
import { Route as DashboardInventariosTiposInsumoRouteRouteImport } from './../../routes/_dashboard/inventarios/tipos-insumo/route'
import { Route as DashboardMantenimientosIndexRouteImport } from './../../routes/_dashboard/mantenimientos/index'
import { Route as DashboardMantenimientosActividadesRouteRouteImport } from './../../routes/_dashboard/mantenimientos/actividades/route'
import { Route as DashboardMantenimientosChecklistsRouteRouteImport } from './../../routes/_dashboard/mantenimientos/checklists/route'
import { Route as DashboardMantenimientosPrioridadesRouteRouteImport } from './../../routes/_dashboard/mantenimientos/prioridades/route'
import { Route as DashboardMantenimientosSolicitudesRouteRouteImport } from './../../routes/_dashboard/mantenimientos/solicitudes/route'
import { Route as DashboardMantenimientosTiposMantenimientoRouteRouteImport } from './../../routes/_dashboard/mantenimientos/tipos-mantenimiento/route'
import { Route as DashboardOrganizacionIndexRouteImport } from './../../routes/_dashboard/organizacion/index'
import { Route as DashboardParametrosCatalogosRouteImport } from './../../routes/_dashboard/parametros/catalogos'
import { Route as DashboardParametrosGestionRouteImport } from './../../routes/_dashboard/parametros/gestion'
import { Route as DashboardParametrosTiposDatoRouteImport } from './../../routes/_dashboard/parametros/tipos-dato'
import { Route as DashboardParametrosUbicacionesRouteImport } from './../../routes/_dashboard/parametros/ubicaciones'
import { Route as DashboardParametrosUnidadesMedidaRouteImport } from './../../routes/_dashboard/parametros/unidades-medida'
import { Route as DashboardTiposActivoIndexRouteImport } from './../../routes/_dashboard/tipos-activo/index'
import { Route as DashboardTiposActivoTipoActivoIdRouteRouteImport } from './../../routes/_dashboard/tipos-activo/$tipoActivoId/route'
import { Route as DashboardTiposActivoHistorialRouteImport } from './../../routes/_dashboard/tipos-activo/historial'
import { Route as DashboardTiposDocumentoIndexRouteImport } from './../../routes/_dashboard/tipos-documento/index'
import { Route as DashboardActivosActivoIdIndexRouteImport } from './../../routes/_dashboard/activos/$activoId/index'
import { Route as DashboardActivosActivoIdEditarRouteImport } from './../../routes/_dashboard/activos/$activoId/editar'
import { Route as DashboardActivosCatalogoIndexRouteImport } from './../../routes/_dashboard/activos/catalogo/index'
import { Route as DashboardActivosCatalogoActivoIdRouteImport } from './../../routes/_dashboard/activos/catalogo/$activoId'
import { Route as DashboardInventariosInsumoIdEditarRouteImport } from './../../routes/_dashboard/inventarios/$insumoId/editar'
import { Route as DashboardInventariosCategoriasIndexRouteImport } from './../../routes/_dashboard/inventarios/categorias/index'
import { Route as DashboardInventariosTiposInsumoIndexRouteImport } from './../../routes/_dashboard/inventarios/tipos-insumo/index'
import { Route as DashboardInventariosTiposInsumoTipoInsumoIdRouteRouteImport } from './../../routes/_dashboard/inventarios/tipos-insumo/$tipoInsumoId/route'
import { Route as DashboardMantenimientosActividadesIndexRouteImport } from './../../routes/_dashboard/mantenimientos/actividades/index'
import { Route as DashboardMantenimientosChecklistsIndexRouteImport } from './../../routes/_dashboard/mantenimientos/checklists/index'
import { Route as DashboardMantenimientosPrioridadesIndexRouteImport } from './../../routes/_dashboard/mantenimientos/prioridades/index'
import { Route as DashboardMantenimientosSolicitudesIndexRouteImport } from './../../routes/_dashboard/mantenimientos/solicitudes/index'
import { Route as DashboardMantenimientosTiposMantenimientoIndexRouteImport } from './../../routes/_dashboard/mantenimientos/tipos-mantenimiento/index'
import { Route as DashboardOrganizacionAreasIndexRouteImport } from './../../routes/_dashboard/organizacion/areas/index'
import { Route as DashboardOrganizacionCargosIndexRouteImport } from './../../routes/_dashboard/organizacion/cargos/index'
import { Route as DashboardOrganizacionEmpleadosIndexRouteImport } from './../../routes/_dashboard/organizacion/empleados/index'
import { Route as DashboardOrganizacionMigracionesIndexRouteImport } from './../../routes/_dashboard/organizacion/migraciones/index'
import { Route as DashboardOrganizacionPersonasIndexRouteImport } from './../../routes/_dashboard/organizacion/personas/index'
import { Route as DashboardTiposActivoTipoActivoIdIndexRouteImport } from './../../routes/_dashboard/tipos-activo/$tipoActivoId/index'
import { Route as DashboardTiposActivoTipoActivoIdAtributosRouteImport } from './../../routes/_dashboard/tipos-activo/$tipoActivoId/atributos'
import { Route as DashboardTiposActivoTipoActivoIdComponentesRouteImport } from './../../routes/_dashboard/tipos-activo/$tipoActivoId/componentes'
import { Route as DashboardInventariosTiposInsumoTipoInsumoIdIndexRouteImport } from './../../routes/_dashboard/inventarios/tipos-insumo/$tipoInsumoId/index'
import { Route as DashboardInventariosTiposInsumoTipoInsumoIdAtributosRouteImport } from './../../routes/_dashboard/inventarios/tipos-insumo/$tipoInsumoId/atributos'

const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAccesoriosRouteRoute =
  DashboardAccesoriosRouteRouteImport.update({
    id: '/accesorios',
    path: '/accesorios',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardActivosRouteRoute = DashboardActivosRouteRouteImport.update({
  id: '/activos',
  path: '/activos',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCategoriasRouteRoute =
  DashboardCategoriasRouteRouteImport.update({
    id: '/categorias',
    path: '/categorias',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardInventariosRouteRoute =
  DashboardInventariosRouteRouteImport.update({
    id: '/inventarios',
    path: '/inventarios',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardMantenimientosRouteRoute =
  DashboardMantenimientosRouteRouteImport.update({
    id: '/mantenimientos',
    path: '/mantenimientos',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardOrganizacionRouteRoute =
  DashboardOrganizacionRouteRouteImport.update({
    id: '/organizacion',
    path: '/organizacion',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardParametrosRouteRoute =
  DashboardParametrosRouteRouteImport.update({
    id: '/parametros',
    path: '/parametros',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPerfilRoute = DashboardPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTiposActivoRouteRoute =
  DashboardTiposActivoRouteRouteImport.update({
    id: '/tipos-activo',
    path: '/tipos-activo',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardTiposDocumentoRouteRoute =
  DashboardTiposDocumentoRouteRouteImport.update({
    id: '/tipos-documento',
    path: '/tipos-documento',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAccesoriosIndexRoute =
  DashboardAccesoriosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardAccesoriosRouteRoute,
  } as any)
const DashboardActivosIndexRoute = DashboardActivosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardActivosRouteRoute,
} as any)
const DashboardActivosConsultaDocumentosRoute =
  DashboardActivosConsultaDocumentosRouteImport.update({
    id: '/consulta-documentos',
    path: '/consulta-documentos',
    getParentRoute: () => DashboardActivosRouteRoute,
  } as any)
const DashboardActivosNuevoRoute = DashboardActivosNuevoRouteImport.update({
  id: '/nuevo',
  path: '/nuevo',
  getParentRoute: () => DashboardActivosRouteRoute,
} as any)
const DashboardCategoriasIndexRoute =
  DashboardCategoriasIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardCategoriasRouteRoute,
  } as any)
const DashboardInventariosIndexRoute =
  DashboardInventariosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardInventariosRouteRoute,
  } as any)
const DashboardInventariosCategoriasRouteRoute =
  DashboardInventariosCategoriasRouteRouteImport.update({
    id: '/categorias',
    path: '/categorias',
    getParentRoute: () => DashboardInventariosRouteRoute,
  } as any)
const DashboardInventariosNuevoRoute =
  DashboardInventariosNuevoRouteImport.update({
    id: '/nuevo',
    path: '/nuevo',
    getParentRoute: () => DashboardInventariosRouteRoute,
  } as any)
const DashboardInventariosTiposInsumoRouteRoute =
  DashboardInventariosTiposInsumoRouteRouteImport.update({
    id: '/tipos-insumo',
    path: '/tipos-insumo',
    getParentRoute: () => DashboardInventariosRouteRoute,
  } as any)
const DashboardMantenimientosIndexRoute =
  DashboardMantenimientosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardMantenimientosRouteRoute,
  } as any)
const DashboardMantenimientosActividadesRouteRoute =
  DashboardMantenimientosActividadesRouteRouteImport.update({
    id: '/actividades',
    path: '/actividades',
    getParentRoute: () => DashboardMantenimientosRouteRoute,
  } as any)
const DashboardMantenimientosChecklistsRouteRoute =
  DashboardMantenimientosChecklistsRouteRouteImport.update({
    id: '/checklists',
    path: '/checklists',
    getParentRoute: () => DashboardMantenimientosRouteRoute,
  } as any)
const DashboardMantenimientosPrioridadesRouteRoute =
  DashboardMantenimientosPrioridadesRouteRouteImport.update({
    id: '/prioridades',
    path: '/prioridades',
    getParentRoute: () => DashboardMantenimientosRouteRoute,
  } as any)
const DashboardMantenimientosSolicitudesRouteRoute =
  DashboardMantenimientosSolicitudesRouteRouteImport.update({
    id: '/solicitudes',
    path: '/solicitudes',
    getParentRoute: () => DashboardMantenimientosRouteRoute,
  } as any)
const DashboardMantenimientosTiposMantenimientoRouteRoute =
  DashboardMantenimientosTiposMantenimientoRouteRouteImport.update({
    id: '/tipos-mantenimiento',
    path: '/tipos-mantenimiento',
    getParentRoute: () => DashboardMantenimientosRouteRoute,
  } as any)
const DashboardOrganizacionIndexRoute =
  DashboardOrganizacionIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardOrganizacionRouteRoute,
  } as any)
const DashboardParametrosCatalogosRoute =
  DashboardParametrosCatalogosRouteImport.update({
    id: '/catalogos',
    path: '/catalogos',
    getParentRoute: () => DashboardParametrosRouteRoute,
  } as any)
const DashboardParametrosGestionRoute =
  DashboardParametrosGestionRouteImport.update({
    id: '/gestion',
    path: '/gestion',
    getParentRoute: () => DashboardParametrosRouteRoute,
  } as any)
const DashboardParametrosTiposDatoRoute =
  DashboardParametrosTiposDatoRouteImport.update({
    id: '/tipos-dato',
    path: '/tipos-dato',
    getParentRoute: () => DashboardParametrosRouteRoute,
  } as any)
const DashboardParametrosUbicacionesRoute =
  DashboardParametrosUbicacionesRouteImport.update({
    id: '/ubicaciones',
    path: '/ubicaciones',
    getParentRoute: () => DashboardParametrosRouteRoute,
  } as any)
const DashboardParametrosUnidadesMedidaRoute =
  DashboardParametrosUnidadesMedidaRouteImport.update({
    id: '/unidades-medida',
    path: '/unidades-medida',
    getParentRoute: () => DashboardParametrosRouteRoute,
  } as any)
const DashboardTiposActivoIndexRoute =
  DashboardTiposActivoIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardTiposActivoRouteRoute,
  } as any)
const DashboardTiposActivoTipoActivoIdRouteRoute =
  DashboardTiposActivoTipoActivoIdRouteRouteImport.update({
    id: '/$tipoActivoId',
    path: '/$tipoActivoId',
    getParentRoute: () => DashboardTiposActivoRouteRoute,
  } as any)
const DashboardTiposActivoHistorialRoute =
  DashboardTiposActivoHistorialRouteImport.update({
    id: '/historial',
    path: '/historial',
    getParentRoute: () => DashboardTiposActivoRouteRoute,
  } as any)
const DashboardTiposDocumentoIndexRoute =
  DashboardTiposDocumentoIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardTiposDocumentoRouteRoute,
  } as any)
const DashboardActivosActivoIdIndexRoute =
  DashboardActivosActivoIdIndexRouteImport.update({
    id: '/$activoId/',
    path: '/$activoId/',
    getParentRoute: () => DashboardActivosRouteRoute,
  } as any)
const DashboardActivosActivoIdEditarRoute =
  DashboardActivosActivoIdEditarRouteImport.update({
    id: '/$activoId/editar',
    path: '/$activoId/editar',
    getParentRoute: () => DashboardActivosRouteRoute,
  } as any)
const DashboardActivosCatalogoIndexRoute =
  DashboardActivosCatalogoIndexRouteImport.update({
    id: '/catalogo/',
    path: '/catalogo/',
    getParentRoute: () => DashboardActivosRouteRoute,
  } as any)
const DashboardActivosCatalogoActivoIdRoute =
  DashboardActivosCatalogoActivoIdRouteImport.update({
    id: '/catalogo/$activoId',
    path: '/catalogo/$activoId',
    getParentRoute: () => DashboardActivosRouteRoute,
  } as any)
const DashboardInventariosInsumoIdEditarRoute =
  DashboardInventariosInsumoIdEditarRouteImport.update({
    id: '/$insumoId/editar',
    path: '/$insumoId/editar',
    getParentRoute: () => DashboardInventariosRouteRoute,
  } as any)
const DashboardInventariosCategoriasIndexRoute =
  DashboardInventariosCategoriasIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardInventariosCategoriasRouteRoute,
  } as any)
const DashboardInventariosTiposInsumoIndexRoute =
  DashboardInventariosTiposInsumoIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardInventariosTiposInsumoRouteRoute,
  } as any)
const DashboardInventariosTiposInsumoTipoInsumoIdRouteRoute =
  DashboardInventariosTiposInsumoTipoInsumoIdRouteRouteImport.update({
    id: '/$tipoInsumoId',
    path: '/$tipoInsumoId',
    getParentRoute: () => DashboardInventariosTiposInsumoRouteRoute,
  } as any)
const DashboardMantenimientosActividadesIndexRoute =
  DashboardMantenimientosActividadesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardMantenimientosActividadesRouteRoute,
  } as any)
const DashboardMantenimientosChecklistsIndexRoute =
  DashboardMantenimientosChecklistsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardMantenimientosChecklistsRouteRoute,
  } as any)
const DashboardMantenimientosPrioridadesIndexRoute =
  DashboardMantenimientosPrioridadesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardMantenimientosPrioridadesRouteRoute,
  } as any)
const DashboardMantenimientosSolicitudesIndexRoute =
  DashboardMantenimientosSolicitudesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardMantenimientosSolicitudesRouteRoute,
  } as any)
const DashboardMantenimientosTiposMantenimientoIndexRoute =
  DashboardMantenimientosTiposMantenimientoIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardMantenimientosTiposMantenimientoRouteRoute,
  } as any)
const DashboardOrganizacionAreasIndexRoute =
  DashboardOrganizacionAreasIndexRouteImport.update({
    id: '/areas/',
    path: '/areas/',
    getParentRoute: () => DashboardOrganizacionRouteRoute,
  } as any)
const DashboardOrganizacionCargosIndexRoute =
  DashboardOrganizacionCargosIndexRouteImport.update({
    id: '/cargos/',
    path: '/cargos/',
    getParentRoute: () => DashboardOrganizacionRouteRoute,
  } as any)
const DashboardOrganizacionEmpleadosIndexRoute =
  DashboardOrganizacionEmpleadosIndexRouteImport.update({
    id: '/empleados/',
    path: '/empleados/',
    getParentRoute: () => DashboardOrganizacionRouteRoute,
  } as any)
const DashboardOrganizacionMigracionesIndexRoute =
  DashboardOrganizacionMigracionesIndexRouteImport.update({
    id: '/migraciones/',
    path: '/migraciones/',
    getParentRoute: () => DashboardOrganizacionRouteRoute,
  } as any)
const DashboardOrganizacionPersonasIndexRoute =
  DashboardOrganizacionPersonasIndexRouteImport.update({
    id: '/personas/',
    path: '/personas/',
    getParentRoute: () => DashboardOrganizacionRouteRoute,
  } as any)
const DashboardTiposActivoTipoActivoIdIndexRoute =
  DashboardTiposActivoTipoActivoIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardTiposActivoTipoActivoIdRouteRoute,
  } as any)
const DashboardTiposActivoTipoActivoIdAtributosRoute =
  DashboardTiposActivoTipoActivoIdAtributosRouteImport.update({
    id: '/atributos',
    path: '/atributos',
    getParentRoute: () => DashboardTiposActivoTipoActivoIdRouteRoute,
  } as any)
const DashboardTiposActivoTipoActivoIdComponentesRoute =
  DashboardTiposActivoTipoActivoIdComponentesRouteImport.update({
    id: '/componentes',
    path: '/componentes',
    getParentRoute: () => DashboardTiposActivoTipoActivoIdRouteRoute,
  } as any)
const DashboardInventariosTiposInsumoTipoInsumoIdIndexRoute =
  DashboardInventariosTiposInsumoTipoInsumoIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardInventariosTiposInsumoTipoInsumoIdRouteRoute,
  } as any)
const DashboardInventariosTiposInsumoTipoInsumoIdAtributosRoute =
  DashboardInventariosTiposInsumoTipoInsumoIdAtributosRouteImport.update({
    id: '/atributos',
    path: '/atributos',
    getParentRoute: () => DashboardInventariosTiposInsumoTipoInsumoIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/login': typeof LoginRoute
  '/accesorios': typeof DashboardAccesoriosRouteRouteWithChildren
  '/activos': typeof DashboardActivosRouteRouteWithChildren
  '/categorias': typeof DashboardCategoriasRouteRouteWithChildren
  '/inventarios': typeof DashboardInventariosRouteRouteWithChildren
  '/mantenimientos': typeof DashboardMantenimientosRouteRouteWithChildren
  '/organizacion': typeof DashboardOrganizacionRouteRouteWithChildren
  '/parametros': typeof DashboardParametrosRouteRouteWithChildren
  '/tipos-activo': typeof DashboardTiposActivoRouteRouteWithChildren
  '/tipos-documento': typeof DashboardTiposDocumentoRouteRouteWithChildren
  '/perfil': typeof DashboardPerfilRoute
  '/inventarios/categorias': typeof DashboardInventariosCategoriasRouteRouteWithChildren
  '/inventarios/tipos-insumo': typeof DashboardInventariosTiposInsumoRouteRouteWithChildren
  '/mantenimientos/actividades': typeof DashboardMantenimientosActividadesRouteRouteWithChildren
  '/mantenimientos/checklists': typeof DashboardMantenimientosChecklistsRouteRouteWithChildren
  '/mantenimientos/prioridades': typeof DashboardMantenimientosPrioridadesRouteRouteWithChildren
  '/mantenimientos/solicitudes': typeof DashboardMantenimientosSolicitudesRouteRouteWithChildren
  '/mantenimientos/tipos-mantenimiento': typeof DashboardMantenimientosTiposMantenimientoRouteRouteWithChildren
  '/tipos-activo/$tipoActivoId': typeof DashboardTiposActivoTipoActivoIdRouteRouteWithChildren
  '/activos/consulta-documentos': typeof DashboardActivosConsultaDocumentosRoute
  '/activos/nuevo': typeof DashboardActivosNuevoRoute
  '/inventarios/nuevo': typeof DashboardInventariosNuevoRoute
  '/parametros/catalogos': typeof DashboardParametrosCatalogosRoute
  '/parametros/gestion': typeof DashboardParametrosGestionRoute
  '/parametros/tipos-dato': typeof DashboardParametrosTiposDatoRoute
  '/parametros/ubicaciones': typeof DashboardParametrosUbicacionesRoute
  '/parametros/unidades-medida': typeof DashboardParametrosUnidadesMedidaRoute
  '/tipos-activo/historial': typeof DashboardTiposActivoHistorialRoute
  '/accesorios/': typeof DashboardAccesoriosIndexRoute
  '/activos/': typeof DashboardActivosIndexRoute
  '/categorias/': typeof DashboardCategoriasIndexRoute
  '/inventarios/': typeof DashboardInventariosIndexRoute
  '/mantenimientos/': typeof DashboardMantenimientosIndexRoute
  '/organizacion/': typeof DashboardOrganizacionIndexRoute
  '/tipos-activo/': typeof DashboardTiposActivoIndexRoute
  '/tipos-documento/': typeof DashboardTiposDocumentoIndexRoute
  '/inventarios/tipos-insumo/$tipoInsumoId': typeof DashboardInventariosTiposInsumoTipoInsumoIdRouteRouteWithChildren
  '/activos/$activoId/editar': typeof DashboardActivosActivoIdEditarRoute
  '/activos/catalogo/$activoId': typeof DashboardActivosCatalogoActivoIdRoute
  '/inventarios/$insumoId/editar': typeof DashboardInventariosInsumoIdEditarRoute
  '/tipos-activo/$tipoActivoId/atributos': typeof DashboardTiposActivoTipoActivoIdAtributosRoute
  '/tipos-activo/$tipoActivoId/componentes': typeof DashboardTiposActivoTipoActivoIdComponentesRoute
  '/activos/$activoId/': typeof DashboardActivosActivoIdIndexRoute
  '/activos/catalogo/': typeof DashboardActivosCatalogoIndexRoute
  '/inventarios/categorias/': typeof DashboardInventariosCategoriasIndexRoute
  '/inventarios/tipos-insumo/': typeof DashboardInventariosTiposInsumoIndexRoute
  '/mantenimientos/actividades/': typeof DashboardMantenimientosActividadesIndexRoute
  '/mantenimientos/checklists/': typeof DashboardMantenimientosChecklistsIndexRoute
  '/mantenimientos/prioridades/': typeof DashboardMantenimientosPrioridadesIndexRoute
  '/mantenimientos/solicitudes/': typeof DashboardMantenimientosSolicitudesIndexRoute
  '/mantenimientos/tipos-mantenimiento/': typeof DashboardMantenimientosTiposMantenimientoIndexRoute
  '/organizacion/areas/': typeof DashboardOrganizacionAreasIndexRoute
  '/organizacion/cargos/': typeof DashboardOrganizacionCargosIndexRoute
  '/organizacion/empleados/': typeof DashboardOrganizacionEmpleadosIndexRoute
  '/organizacion/migraciones/': typeof DashboardOrganizacionMigracionesIndexRoute
  '/organizacion/personas/': typeof DashboardOrganizacionPersonasIndexRoute
  '/tipos-activo/$tipoActivoId/': typeof DashboardTiposActivoTipoActivoIdIndexRoute
  '/inventarios/tipos-insumo/$tipoInsumoId/atributos': typeof DashboardInventariosTiposInsumoTipoInsumoIdAtributosRoute
  '/inventarios/tipos-insumo/$tipoInsumoId/': typeof DashboardInventariosTiposInsumoTipoInsumoIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/parametros': typeof DashboardParametrosRouteRouteWithChildren
  '/perfil': typeof DashboardPerfilRoute
  '/': typeof DashboardIndexRoute
  '/activos/consulta-documentos': typeof DashboardActivosConsultaDocumentosRoute
  '/activos/nuevo': typeof DashboardActivosNuevoRoute
  '/inventarios/nuevo': typeof DashboardInventariosNuevoRoute
  '/parametros/catalogos': typeof DashboardParametrosCatalogosRoute
  '/parametros/gestion': typeof DashboardParametrosGestionRoute
  '/parametros/tipos-dato': typeof DashboardParametrosTiposDatoRoute
  '/parametros/ubicaciones': typeof DashboardParametrosUbicacionesRoute
  '/parametros/unidades-medida': typeof DashboardParametrosUnidadesMedidaRoute
  '/tipos-activo/historial': typeof DashboardTiposActivoHistorialRoute
  '/accesorios': typeof DashboardAccesoriosIndexRoute
  '/activos': typeof DashboardActivosIndexRoute
  '/categorias': typeof DashboardCategoriasIndexRoute
  '/inventarios': typeof DashboardInventariosIndexRoute
  '/mantenimientos': typeof DashboardMantenimientosIndexRoute
  '/organizacion': typeof DashboardOrganizacionIndexRoute
  '/tipos-activo': typeof DashboardTiposActivoIndexRoute
  '/tipos-documento': typeof DashboardTiposDocumentoIndexRoute
  '/activos/$activoId/editar': typeof DashboardActivosActivoIdEditarRoute
  '/activos/catalogo/$activoId': typeof DashboardActivosCatalogoActivoIdRoute
  '/inventarios/$insumoId/editar': typeof DashboardInventariosInsumoIdEditarRoute
  '/tipos-activo/$tipoActivoId/atributos': typeof DashboardTiposActivoTipoActivoIdAtributosRoute
  '/tipos-activo/$tipoActivoId/componentes': typeof DashboardTiposActivoTipoActivoIdComponentesRoute
  '/activos/$activoId': typeof DashboardActivosActivoIdIndexRoute
  '/activos/catalogo': typeof DashboardActivosCatalogoIndexRoute
  '/inventarios/categorias': typeof DashboardInventariosCategoriasIndexRoute
  '/inventarios/tipos-insumo': typeof DashboardInventariosTiposInsumoIndexRoute
  '/mantenimientos/actividades': typeof DashboardMantenimientosActividadesIndexRoute
  '/mantenimientos/checklists': typeof DashboardMantenimientosChecklistsIndexRoute
  '/mantenimientos/prioridades': typeof DashboardMantenimientosPrioridadesIndexRoute
  '/mantenimientos/solicitudes': typeof DashboardMantenimientosSolicitudesIndexRoute
  '/mantenimientos/tipos-mantenimiento': typeof DashboardMantenimientosTiposMantenimientoIndexRoute
  '/organizacion/areas': typeof DashboardOrganizacionAreasIndexRoute
  '/organizacion/cargos': typeof DashboardOrganizacionCargosIndexRoute
  '/organizacion/empleados': typeof DashboardOrganizacionEmpleadosIndexRoute
  '/organizacion/migraciones': typeof DashboardOrganizacionMigracionesIndexRoute
  '/organizacion/personas': typeof DashboardOrganizacionPersonasIndexRoute
  '/tipos-activo/$tipoActivoId': typeof DashboardTiposActivoTipoActivoIdIndexRoute
  '/inventarios/tipos-insumo/$tipoInsumoId/atributos': typeof DashboardInventariosTiposInsumoTipoInsumoIdAtributosRoute
  '/inventarios/tipos-insumo/$tipoInsumoId': typeof DashboardInventariosTiposInsumoTipoInsumoIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/_dashboard/accesorios': typeof DashboardAccesoriosRouteRouteWithChildren
  '/_dashboard/activos': typeof DashboardActivosRouteRouteWithChildren
  '/_dashboard/categorias': typeof DashboardCategoriasRouteRouteWithChildren
  '/_dashboard/inventarios': typeof DashboardInventariosRouteRouteWithChildren
  '/_dashboard/mantenimientos': typeof DashboardMantenimientosRouteRouteWithChildren
  '/_dashboard/organizacion': typeof DashboardOrganizacionRouteRouteWithChildren
  '/_dashboard/parametros': typeof DashboardParametrosRouteRouteWithChildren
  '/_dashboard/tipos-activo': typeof DashboardTiposActivoRouteRouteWithChildren
  '/_dashboard/tipos-documento': typeof DashboardTiposDocumentoRouteRouteWithChildren
  '/_dashboard/perfil': typeof DashboardPerfilRoute
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/inventarios/categorias': typeof DashboardInventariosCategoriasRouteRouteWithChildren
  '/_dashboard/inventarios/tipos-insumo': typeof DashboardInventariosTiposInsumoRouteRouteWithChildren
  '/_dashboard/mantenimientos/actividades': typeof DashboardMantenimientosActividadesRouteRouteWithChildren
  '/_dashboard/mantenimientos/checklists': typeof DashboardMantenimientosChecklistsRouteRouteWithChildren
  '/_dashboard/mantenimientos/prioridades': typeof DashboardMantenimientosPrioridadesRouteRouteWithChildren
  '/_dashboard/mantenimientos/solicitudes': typeof DashboardMantenimientosSolicitudesRouteRouteWithChildren
  '/_dashboard/mantenimientos/tipos-mantenimiento': typeof DashboardMantenimientosTiposMantenimientoRouteRouteWithChildren
  '/_dashboard/tipos-activo/$tipoActivoId': typeof DashboardTiposActivoTipoActivoIdRouteRouteWithChildren
  '/_dashboard/activos/consulta-documentos': typeof DashboardActivosConsultaDocumentosRoute
  '/_dashboard/activos/nuevo': typeof DashboardActivosNuevoRoute
  '/_dashboard/inventarios/nuevo': typeof DashboardInventariosNuevoRoute
  '/_dashboard/parametros/catalogos': typeof DashboardParametrosCatalogosRoute
  '/_dashboard/parametros/gestion': typeof DashboardParametrosGestionRoute
  '/_dashboard/parametros/tipos-dato': typeof DashboardParametrosTiposDatoRoute
  '/_dashboard/parametros/ubicaciones': typeof DashboardParametrosUbicacionesRoute
  '/_dashboard/parametros/unidades-medida': typeof DashboardParametrosUnidadesMedidaRoute
  '/_dashboard/tipos-activo/historial': typeof DashboardTiposActivoHistorialRoute
  '/_dashboard/accesorios/': typeof DashboardAccesoriosIndexRoute
  '/_dashboard/activos/': typeof DashboardActivosIndexRoute
  '/_dashboard/categorias/': typeof DashboardCategoriasIndexRoute
  '/_dashboard/inventarios/': typeof DashboardInventariosIndexRoute
  '/_dashboard/mantenimientos/': typeof DashboardMantenimientosIndexRoute
  '/_dashboard/organizacion/': typeof DashboardOrganizacionIndexRoute
  '/_dashboard/tipos-activo/': typeof DashboardTiposActivoIndexRoute
  '/_dashboard/tipos-documento/': typeof DashboardTiposDocumentoIndexRoute
  '/_dashboard/inventarios/tipos-insumo/$tipoInsumoId': typeof DashboardInventariosTiposInsumoTipoInsumoIdRouteRouteWithChildren
  '/_dashboard/activos/$activoId/editar': typeof DashboardActivosActivoIdEditarRoute
  '/_dashboard/activos/catalogo/$activoId': typeof DashboardActivosCatalogoActivoIdRoute
  '/_dashboard/inventarios/$insumoId/editar': typeof DashboardInventariosInsumoIdEditarRoute
  '/_dashboard/tipos-activo/$tipoActivoId/atributos': typeof DashboardTiposActivoTipoActivoIdAtributosRoute
  '/_dashboard/tipos-activo/$tipoActivoId/componentes': typeof DashboardTiposActivoTipoActivoIdComponentesRoute
  '/_dashboard/activos/$activoId/': typeof DashboardActivosActivoIdIndexRoute
  '/_dashboard/activos/catalogo/': typeof DashboardActivosCatalogoIndexRoute
  '/_dashboard/inventarios/categorias/': typeof DashboardInventariosCategoriasIndexRoute
  '/_dashboard/inventarios/tipos-insumo/': typeof DashboardInventariosTiposInsumoIndexRoute
  '/_dashboard/mantenimientos/actividades/': typeof DashboardMantenimientosActividadesIndexRoute
  '/_dashboard/mantenimientos/checklists/': typeof DashboardMantenimientosChecklistsIndexRoute
  '/_dashboard/mantenimientos/prioridades/': typeof DashboardMantenimientosPrioridadesIndexRoute
  '/_dashboard/mantenimientos/solicitudes/': typeof DashboardMantenimientosSolicitudesIndexRoute
  '/_dashboard/mantenimientos/tipos-mantenimiento/': typeof DashboardMantenimientosTiposMantenimientoIndexRoute
  '/_dashboard/organizacion/areas/': typeof DashboardOrganizacionAreasIndexRoute
  '/_dashboard/organizacion/cargos/': typeof DashboardOrganizacionCargosIndexRoute
  '/_dashboard/organizacion/empleados/': typeof DashboardOrganizacionEmpleadosIndexRoute
  '/_dashboard/organizacion/migraciones/': typeof DashboardOrganizacionMigracionesIndexRoute
  '/_dashboard/organizacion/personas/': typeof DashboardOrganizacionPersonasIndexRoute
  '/_dashboard/tipos-activo/$tipoActivoId/': typeof DashboardTiposActivoTipoActivoIdIndexRoute
  '/_dashboard/inventarios/tipos-insumo/$tipoInsumoId/atributos': typeof DashboardInventariosTiposInsumoTipoInsumoIdAtributosRoute
  '/_dashboard/inventarios/tipos-insumo/$tipoInsumoId/': typeof DashboardInventariosTiposInsumoTipoInsumoIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/accesorios'
    | '/activos'
    | '/categorias'
    | '/inventarios'
    | '/mantenimientos'
    | '/organizacion'
    | '/parametros'
    | '/tipos-activo'
    | '/tipos-documento'
    | '/perfil'
    | '/inventarios/categorias'
    | '/inventarios/tipos-insumo'
    | '/mantenimientos/actividades'
    | '/mantenimientos/checklists'
    | '/mantenimientos/prioridades'
    | '/mantenimientos/solicitudes'
    | '/mantenimientos/tipos-mantenimiento'
    | '/tipos-activo/$tipoActivoId'
    | '/activos/consulta-documentos'
    | '/activos/nuevo'
    | '/inventarios/nuevo'
    | '/parametros/catalogos'
    | '/parametros/gestion'
    | '/parametros/tipos-dato'
    | '/parametros/ubicaciones'
    | '/parametros/unidades-medida'
    | '/tipos-activo/historial'
    | '/accesorios/'
    | '/activos/'
    | '/categorias/'
    | '/inventarios/'
    | '/mantenimientos/'
    | '/organizacion/'
    | '/tipos-activo/'
    | '/tipos-documento/'
    | '/inventarios/tipos-insumo/$tipoInsumoId'
    | '/activos/$activoId/editar'
    | '/activos/catalogo/$activoId'
    | '/inventarios/$insumoId/editar'
    | '/tipos-activo/$tipoActivoId/atributos'
    | '/tipos-activo/$tipoActivoId/componentes'
    | '/activos/$activoId/'
    | '/activos/catalogo/'
    | '/inventarios/categorias/'
    | '/inventarios/tipos-insumo/'
    | '/mantenimientos/actividades/'
    | '/mantenimientos/checklists/'
    | '/mantenimientos/prioridades/'
    | '/mantenimientos/solicitudes/'
    | '/mantenimientos/tipos-mantenimiento/'
    | '/organizacion/areas/'
    | '/organizacion/cargos/'
    | '/organizacion/empleados/'
    | '/organizacion/migraciones/'
    | '/organizacion/personas/'
    | '/tipos-activo/$tipoActivoId/'
    | '/inventarios/tipos-insumo/$tipoInsumoId/atributos'
    | '/inventarios/tipos-insumo/$tipoInsumoId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/parametros'
    | '/perfil'
    | '/'
    | '/activos/consulta-documentos'
    | '/activos/nuevo'
    | '/inventarios/nuevo'
    | '/parametros/catalogos'
    | '/parametros/gestion'
    | '/parametros/tipos-dato'
    | '/parametros/ubicaciones'
    | '/parametros/unidades-medida'
    | '/tipos-activo/historial'
    | '/accesorios'
    | '/activos'
    | '/categorias'
    | '/inventarios'
    | '/mantenimientos'
    | '/organizacion'
    | '/tipos-activo'
    | '/tipos-documento'
    | '/activos/$activoId/editar'
    | '/activos/catalogo/$activoId'
    | '/inventarios/$insumoId/editar'
    | '/tipos-activo/$tipoActivoId/atributos'
    | '/tipos-activo/$tipoActivoId/componentes'
    | '/activos/$activoId'
    | '/activos/catalogo'
    | '/inventarios/categorias'
    | '/inventarios/tipos-insumo'
    | '/mantenimientos/actividades'
    | '/mantenimientos/checklists'
    | '/mantenimientos/prioridades'
    | '/mantenimientos/solicitudes'
    | '/mantenimientos/tipos-mantenimiento'
    | '/organizacion/areas'
    | '/organizacion/cargos'
    | '/organizacion/empleados'
    | '/organizacion/migraciones'
    | '/organizacion/personas'
    | '/tipos-activo/$tipoActivoId'
    | '/inventarios/tipos-insumo/$tipoInsumoId/atributos'
    | '/inventarios/tipos-insumo/$tipoInsumoId'
  id:
    | '__root__'
    | '/_dashboard'
    | '/login'
    | '/_dashboard/accesorios'
    | '/_dashboard/activos'
    | '/_dashboard/categorias'
    | '/_dashboard/inventarios'
    | '/_dashboard/mantenimientos'
    | '/_dashboard/organizacion'
    | '/_dashboard/parametros'
    | '/_dashboard/tipos-activo'
    | '/_dashboard/tipos-documento'
    | '/_dashboard/perfil'
    | '/_dashboard/'
    | '/_dashboard/inventarios/categorias'
    | '/_dashboard/inventarios/tipos-insumo'
    | '/_dashboard/mantenimientos/actividades'
    | '/_dashboard/mantenimientos/checklists'
    | '/_dashboard/mantenimientos/prioridades'
    | '/_dashboard/mantenimientos/solicitudes'
    | '/_dashboard/mantenimientos/tipos-mantenimiento'
    | '/_dashboard/tipos-activo/$tipoActivoId'
    | '/_dashboard/activos/consulta-documentos'
    | '/_dashboard/activos/nuevo'
    | '/_dashboard/inventarios/nuevo'
    | '/_dashboard/parametros/catalogos'
    | '/_dashboard/parametros/gestion'
    | '/_dashboard/parametros/tipos-dato'
    | '/_dashboard/parametros/ubicaciones'
    | '/_dashboard/parametros/unidades-medida'
    | '/_dashboard/tipos-activo/historial'
    | '/_dashboard/accesorios/'
    | '/_dashboard/activos/'
    | '/_dashboard/categorias/'
    | '/_dashboard/inventarios/'
    | '/_dashboard/mantenimientos/'
    | '/_dashboard/organizacion/'
    | '/_dashboard/tipos-activo/'
    | '/_dashboard/tipos-documento/'
    | '/_dashboard/inventarios/tipos-insumo/$tipoInsumoId'
    | '/_dashboard/activos/$activoId/editar'
    | '/_dashboard/activos/catalogo/$activoId'
    | '/_dashboard/inventarios/$insumoId/editar'
    | '/_dashboard/tipos-activo/$tipoActivoId/atributos'
    | '/_dashboard/tipos-activo/$tipoActivoId/componentes'
    | '/_dashboard/activos/$activoId/'
    | '/_dashboard/activos/catalogo/'
    | '/_dashboard/inventarios/categorias/'
    | '/_dashboard/inventarios/tipos-insumo/'
    | '/_dashboard/mantenimientos/actividades/'
    | '/_dashboard/mantenimientos/checklists/'
    | '/_dashboard/mantenimientos/prioridades/'
    | '/_dashboard/mantenimientos/solicitudes/'
    | '/_dashboard/mantenimientos/tipos-mantenimiento/'
    | '/_dashboard/organizacion/areas/'
    | '/_dashboard/organizacion/cargos/'
    | '/_dashboard/organizacion/empleados/'
    | '/_dashboard/organizacion/migraciones/'
    | '/_dashboard/organizacion/personas/'
    | '/_dashboard/tipos-activo/$tipoActivoId/'
    | '/_dashboard/inventarios/tipos-insumo/$tipoInsumoId/atributos'
    | '/_dashboard/inventarios/tipos-insumo/$tipoInsumoId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/accesorios': {
      id: '/_dashboard/accesorios'
      path: '/accesorios'
      fullPath: '/accesorios'
      preLoaderRoute: typeof DashboardAccesoriosRouteRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/activos': {
      id: '/_dashboard/activos'
      path: '/activos'
      fullPath: '/activos'
      preLoaderRoute: typeof DashboardActivosRouteRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/categorias': {
      id: '/_dashboard/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof DashboardCategoriasRouteRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/inventarios': {
      id: '/_dashboard/inventarios'
      path: '/inventarios'
      fullPath: '/inventarios'
      preLoaderRoute: typeof DashboardInventariosRouteRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/mantenimientos': {
      id: '/_dashboard/mantenimientos'
      path: '/mantenimientos'
      fullPath: '/mantenimientos'
      preLoaderRoute: typeof DashboardMantenimientosRouteRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/organizacion': {
      id: '/_dashboard/organizacion'
      path: '/organizacion'
      fullPath: '/organizacion'
      preLoaderRoute: typeof DashboardOrganizacionRouteRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/parametros': {
      id: '/_dashboard/parametros'
      path: '/parametros'
      fullPath: '/parametros'
      preLoaderRoute: typeof DashboardParametrosRouteRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/perfil': {
      id: '/_dashboard/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof DashboardPerfilRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/tipos-activo': {
      id: '/_dashboard/tipos-activo'
      path: '/tipos-activo'
      fullPath: '/tipos-activo'
      preLoaderRoute: typeof DashboardTiposActivoRouteRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/tipos-documento': {
      id: '/_dashboard/tipos-documento'
      path: '/tipos-documento'
      fullPath: '/tipos-documento'
      preLoaderRoute: typeof DashboardTiposDocumentoRouteRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/accesorios/': {
      id: '/_dashboard/accesorios/'
      path: '/'
      fullPath: '/accesorios/'
      preLoaderRoute: typeof DashboardAccesoriosIndexRouteImport
      parentRoute: typeof DashboardAccesoriosRouteRoute
    }
    '/_dashboard/activos/': {
      id: '/_dashboard/activos/'
      path: '/'
      fullPath: '/activos/'
      preLoaderRoute: typeof DashboardActivosIndexRouteImport
      parentRoute: typeof DashboardActivosRouteRoute
    }
    '/_dashboard/activos/consulta-documentos': {
      id: '/_dashboard/activos/consulta-documentos'
      path: '/consulta-documentos'
      fullPath: '/activos/consulta-documentos'
      preLoaderRoute: typeof DashboardActivosConsultaDocumentosRouteImport
      parentRoute: typeof DashboardActivosRouteRoute
    }
    '/_dashboard/activos/nuevo': {
      id: '/_dashboard/activos/nuevo'
      path: '/nuevo'
      fullPath: '/activos/nuevo'
      preLoaderRoute: typeof DashboardActivosNuevoRouteImport
      parentRoute: typeof DashboardActivosRouteRoute
    }
    '/_dashboard/categorias/': {
      id: '/_dashboard/categorias/'
      path: '/'
      fullPath: '/categorias/'
      preLoaderRoute: typeof DashboardCategoriasIndexRouteImport
      parentRoute: typeof DashboardCategoriasRouteRoute
    }
    '/_dashboard/inventarios/': {
      id: '/_dashboard/inventarios/'
      path: '/'
      fullPath: '/inventarios/'
      preLoaderRoute: typeof DashboardInventariosIndexRouteImport
      parentRoute: typeof DashboardInventariosRouteRoute
    }
    '/_dashboard/inventarios/categorias': {
      id: '/_dashboard/inventarios/categorias'
      path: '/categorias'
      fullPath: '/inventarios/categorias'
      preLoaderRoute: typeof DashboardInventariosCategoriasRouteRouteImport
      parentRoute: typeof DashboardInventariosRouteRoute
    }
    '/_dashboard/inventarios/nuevo': {
      id: '/_dashboard/inventarios/nuevo'
      path: '/nuevo'
      fullPath: '/inventarios/nuevo'
      preLoaderRoute: typeof DashboardInventariosNuevoRouteImport
      parentRoute: typeof DashboardInventariosRouteRoute
    }
    '/_dashboard/inventarios/tipos-insumo': {
      id: '/_dashboard/inventarios/tipos-insumo'
      path: '/tipos-insumo'
      fullPath: '/inventarios/tipos-insumo'
      preLoaderRoute: typeof DashboardInventariosTiposInsumoRouteRouteImport
      parentRoute: typeof DashboardInventariosRouteRoute
    }
    '/_dashboard/mantenimientos/': {
      id: '/_dashboard/mantenimientos/'
      path: '/'
      fullPath: '/mantenimientos/'
      preLoaderRoute: typeof DashboardMantenimientosIndexRouteImport
      parentRoute: typeof DashboardMantenimientosRouteRoute
    }
    '/_dashboard/mantenimientos/actividades': {
      id: '/_dashboard/mantenimientos/actividades'
      path: '/actividades'
      fullPath: '/mantenimientos/actividades'
      preLoaderRoute: typeof DashboardMantenimientosActividadesRouteRouteImport
      parentRoute: typeof DashboardMantenimientosRouteRoute
    }
    '/_dashboard/mantenimientos/checklists': {
      id: '/_dashboard/mantenimientos/checklists'
      path: '/checklists'
      fullPath: '/mantenimientos/checklists'
      preLoaderRoute: typeof DashboardMantenimientosChecklistsRouteRouteImport
      parentRoute: typeof DashboardMantenimientosRouteRoute
    }
    '/_dashboard/mantenimientos/prioridades': {
      id: '/_dashboard/mantenimientos/prioridades'
      path: '/prioridades'
      fullPath: '/mantenimientos/prioridades'
      preLoaderRoute: typeof DashboardMantenimientosPrioridadesRouteRouteImport
      parentRoute: typeof DashboardMantenimientosRouteRoute
    }
    '/_dashboard/mantenimientos/solicitudes': {
      id: '/_dashboard/mantenimientos/solicitudes'
      path: '/solicitudes'
      fullPath: '/mantenimientos/solicitudes'
      preLoaderRoute: typeof DashboardMantenimientosSolicitudesRouteRouteImport
      parentRoute: typeof DashboardMantenimientosRouteRoute
    }
    '/_dashboard/mantenimientos/tipos-mantenimiento': {
      id: '/_dashboard/mantenimientos/tipos-mantenimiento'
      path: '/tipos-mantenimiento'
      fullPath: '/mantenimientos/tipos-mantenimiento'
      preLoaderRoute: typeof DashboardMantenimientosTiposMantenimientoRouteRouteImport
      parentRoute: typeof DashboardMantenimientosRouteRoute
    }
    '/_dashboard/organizacion/': {
      id: '/_dashboard/organizacion/'
      path: '/'
      fullPath: '/organizacion/'
      preLoaderRoute: typeof DashboardOrganizacionIndexRouteImport
      parentRoute: typeof DashboardOrganizacionRouteRoute
    }
    '/_dashboard/parametros/catalogos': {
      id: '/_dashboard/parametros/catalogos'
      path: '/catalogos'
      fullPath: '/parametros/catalogos'
      preLoaderRoute: typeof DashboardParametrosCatalogosRouteImport
      parentRoute: typeof DashboardParametrosRouteRoute
    }
    '/_dashboard/parametros/gestion': {
      id: '/_dashboard/parametros/gestion'
      path: '/gestion'
      fullPath: '/parametros/gestion'
      preLoaderRoute: typeof DashboardParametrosGestionRouteImport
      parentRoute: typeof DashboardParametrosRouteRoute
    }
    '/_dashboard/parametros/tipos-dato': {
      id: '/_dashboard/parametros/tipos-dato'
      path: '/tipos-dato'
      fullPath: '/parametros/tipos-dato'
      preLoaderRoute: typeof DashboardParametrosTiposDatoRouteImport
      parentRoute: typeof DashboardParametrosRouteRoute
    }
    '/_dashboard/parametros/ubicaciones': {
      id: '/_dashboard/parametros/ubicaciones'
      path: '/ubicaciones'
      fullPath: '/parametros/ubicaciones'
      preLoaderRoute: typeof DashboardParametrosUbicacionesRouteImport
      parentRoute: typeof DashboardParametrosRouteRoute
    }
    '/_dashboard/parametros/unidades-medida': {
      id: '/_dashboard/parametros/unidades-medida'
      path: '/unidades-medida'
      fullPath: '/parametros/unidades-medida'
      preLoaderRoute: typeof DashboardParametrosUnidadesMedidaRouteImport
      parentRoute: typeof DashboardParametrosRouteRoute
    }
    '/_dashboard/tipos-activo/': {
      id: '/_dashboard/tipos-activo/'
      path: '/'
      fullPath: '/tipos-activo/'
      preLoaderRoute: typeof DashboardTiposActivoIndexRouteImport
      parentRoute: typeof DashboardTiposActivoRouteRoute
    }
    '/_dashboard/tipos-activo/$tipoActivoId': {
      id: '/_dashboard/tipos-activo/$tipoActivoId'
      path: '/$tipoActivoId'
      fullPath: '/tipos-activo/$tipoActivoId'
      preLoaderRoute: typeof DashboardTiposActivoTipoActivoIdRouteRouteImport
      parentRoute: typeof DashboardTiposActivoRouteRoute
    }
    '/_dashboard/tipos-activo/historial': {
      id: '/_dashboard/tipos-activo/historial'
      path: '/historial'
      fullPath: '/tipos-activo/historial'
      preLoaderRoute: typeof DashboardTiposActivoHistorialRouteImport
      parentRoute: typeof DashboardTiposActivoRouteRoute
    }
    '/_dashboard/tipos-documento/': {
      id: '/_dashboard/tipos-documento/'
      path: '/'
      fullPath: '/tipos-documento/'
      preLoaderRoute: typeof DashboardTiposDocumentoIndexRouteImport
      parentRoute: typeof DashboardTiposDocumentoRouteRoute
    }
    '/_dashboard/activos/$activoId/': {
      id: '/_dashboard/activos/$activoId/'
      path: '/$activoId'
      fullPath: '/activos/$activoId/'
      preLoaderRoute: typeof DashboardActivosActivoIdIndexRouteImport
      parentRoute: typeof DashboardActivosRouteRoute
    }
    '/_dashboard/activos/$activoId/editar': {
      id: '/_dashboard/activos/$activoId/editar'
      path: '/$activoId/editar'
      fullPath: '/activos/$activoId/editar'
      preLoaderRoute: typeof DashboardActivosActivoIdEditarRouteImport
      parentRoute: typeof DashboardActivosRouteRoute
    }
    '/_dashboard/activos/catalogo/': {
      id: '/_dashboard/activos/catalogo/'
      path: '/catalogo'
      fullPath: '/activos/catalogo/'
      preLoaderRoute: typeof DashboardActivosCatalogoIndexRouteImport
      parentRoute: typeof DashboardActivosRouteRoute
    }
    '/_dashboard/activos/catalogo/$activoId': {
      id: '/_dashboard/activos/catalogo/$activoId'
      path: '/catalogo/$activoId'
      fullPath: '/activos/catalogo/$activoId'
      preLoaderRoute: typeof DashboardActivosCatalogoActivoIdRouteImport
      parentRoute: typeof DashboardActivosRouteRoute
    }
    '/_dashboard/inventarios/$insumoId/editar': {
      id: '/_dashboard/inventarios/$insumoId/editar'
      path: '/$insumoId/editar'
      fullPath: '/inventarios/$insumoId/editar'
      preLoaderRoute: typeof DashboardInventariosInsumoIdEditarRouteImport
      parentRoute: typeof DashboardInventariosRouteRoute
    }
    '/_dashboard/inventarios/categorias/': {
      id: '/_dashboard/inventarios/categorias/'
      path: '/'
      fullPath: '/inventarios/categorias/'
      preLoaderRoute: typeof DashboardInventariosCategoriasIndexRouteImport
      parentRoute: typeof DashboardInventariosCategoriasRouteRoute
    }
    '/_dashboard/inventarios/tipos-insumo/': {
      id: '/_dashboard/inventarios/tipos-insumo/'
      path: '/'
      fullPath: '/inventarios/tipos-insumo/'
      preLoaderRoute: typeof DashboardInventariosTiposInsumoIndexRouteImport
      parentRoute: typeof DashboardInventariosTiposInsumoRouteRoute
    }
    '/_dashboard/inventarios/tipos-insumo/$tipoInsumoId': {
      id: '/_dashboard/inventarios/tipos-insumo/$tipoInsumoId'
      path: '/$tipoInsumoId'
      fullPath: '/inventarios/tipos-insumo/$tipoInsumoId'
      preLoaderRoute: typeof DashboardInventariosTiposInsumoTipoInsumoIdRouteRouteImport
      parentRoute: typeof DashboardInventariosTiposInsumoRouteRoute
    }
    '/_dashboard/mantenimientos/actividades/': {
      id: '/_dashboard/mantenimientos/actividades/'
      path: '/'
      fullPath: '/mantenimientos/actividades/'
      preLoaderRoute: typeof DashboardMantenimientosActividadesIndexRouteImport
      parentRoute: typeof DashboardMantenimientosActividadesRouteRoute
    }
    '/_dashboard/mantenimientos/checklists/': {
      id: '/_dashboard/mantenimientos/checklists/'
      path: '/'
      fullPath: '/mantenimientos/checklists/'
      preLoaderRoute: typeof DashboardMantenimientosChecklistsIndexRouteImport
      parentRoute: typeof DashboardMantenimientosChecklistsRouteRoute
    }
    '/_dashboard/mantenimientos/prioridades/': {
      id: '/_dashboard/mantenimientos/prioridades/'
      path: '/'
      fullPath: '/mantenimientos/prioridades/'
      preLoaderRoute: typeof DashboardMantenimientosPrioridadesIndexRouteImport
      parentRoute: typeof DashboardMantenimientosPrioridadesRouteRoute
    }
    '/_dashboard/mantenimientos/solicitudes/': {
      id: '/_dashboard/mantenimientos/solicitudes/'
      path: '/'
      fullPath: '/mantenimientos/solicitudes/'
      preLoaderRoute: typeof DashboardMantenimientosSolicitudesIndexRouteImport
      parentRoute: typeof DashboardMantenimientosSolicitudesRouteRoute
    }
    '/_dashboard/mantenimientos/tipos-mantenimiento/': {
      id: '/_dashboard/mantenimientos/tipos-mantenimiento/'
      path: '/'
      fullPath: '/mantenimientos/tipos-mantenimiento/'
      preLoaderRoute: typeof DashboardMantenimientosTiposMantenimientoIndexRouteImport
      parentRoute: typeof DashboardMantenimientosTiposMantenimientoRouteRoute
    }
    '/_dashboard/organizacion/areas/': {
      id: '/_dashboard/organizacion/areas/'
      path: '/areas'
      fullPath: '/organizacion/areas/'
      preLoaderRoute: typeof DashboardOrganizacionAreasIndexRouteImport
      parentRoute: typeof DashboardOrganizacionRouteRoute
    }
    '/_dashboard/organizacion/cargos/': {
      id: '/_dashboard/organizacion/cargos/'
      path: '/cargos'
      fullPath: '/organizacion/cargos/'
      preLoaderRoute: typeof DashboardOrganizacionCargosIndexRouteImport
      parentRoute: typeof DashboardOrganizacionRouteRoute
    }
    '/_dashboard/organizacion/empleados/': {
      id: '/_dashboard/organizacion/empleados/'
      path: '/empleados'
      fullPath: '/organizacion/empleados/'
      preLoaderRoute: typeof DashboardOrganizacionEmpleadosIndexRouteImport
      parentRoute: typeof DashboardOrganizacionRouteRoute
    }
    '/_dashboard/organizacion/migraciones/': {
      id: '/_dashboard/organizacion/migraciones/'
      path: '/migraciones'
      fullPath: '/organizacion/migraciones/'
      preLoaderRoute: typeof DashboardOrganizacionMigracionesIndexRouteImport
      parentRoute: typeof DashboardOrganizacionRouteRoute
    }
    '/_dashboard/organizacion/personas/': {
      id: '/_dashboard/organizacion/personas/'
      path: '/personas'
      fullPath: '/organizacion/personas/'
      preLoaderRoute: typeof DashboardOrganizacionPersonasIndexRouteImport
      parentRoute: typeof DashboardOrganizacionRouteRoute
    }
    '/_dashboard/tipos-activo/$tipoActivoId/': {
      id: '/_dashboard/tipos-activo/$tipoActivoId/'
      path: '/'
      fullPath: '/tipos-activo/$tipoActivoId/'
      preLoaderRoute: typeof DashboardTiposActivoTipoActivoIdIndexRouteImport
      parentRoute: typeof DashboardTiposActivoTipoActivoIdRouteRoute
    }
    '/_dashboard/tipos-activo/$tipoActivoId/atributos': {
      id: '/_dashboard/tipos-activo/$tipoActivoId/atributos'
      path: '/atributos'
      fullPath: '/tipos-activo/$tipoActivoId/atributos'
      preLoaderRoute: typeof DashboardTiposActivoTipoActivoIdAtributosRouteImport
      parentRoute: typeof DashboardTiposActivoTipoActivoIdRouteRoute
    }
    '/_dashboard/tipos-activo/$tipoActivoId/componentes': {
      id: '/_dashboard/tipos-activo/$tipoActivoId/componentes'
      path: '/componentes'
      fullPath: '/tipos-activo/$tipoActivoId/componentes'
      preLoaderRoute: typeof DashboardTiposActivoTipoActivoIdComponentesRouteImport
      parentRoute: typeof DashboardTiposActivoTipoActivoIdRouteRoute
    }
    '/_dashboard/inventarios/tipos-insumo/$tipoInsumoId/': {
      id: '/_dashboard/inventarios/tipos-insumo/$tipoInsumoId/'
      path: '/'
      fullPath: '/inventarios/tipos-insumo/$tipoInsumoId/'
      preLoaderRoute: typeof DashboardInventariosTiposInsumoTipoInsumoIdIndexRouteImport
      parentRoute: typeof DashboardInventariosTiposInsumoTipoInsumoIdRouteRoute
    }
    '/_dashboard/inventarios/tipos-insumo/$tipoInsumoId/atributos': {
      id: '/_dashboard/inventarios/tipos-insumo/$tipoInsumoId/atributos'
      path: '/atributos'
      fullPath: '/inventarios/tipos-insumo/$tipoInsumoId/atributos'
      preLoaderRoute: typeof DashboardInventariosTiposInsumoTipoInsumoIdAtributosRouteImport
      parentRoute: typeof DashboardInventariosTiposInsumoTipoInsumoIdRouteRoute
    }
  }
}

interface DashboardAccesoriosRouteRouteChildren {
  DashboardAccesoriosIndexRoute: typeof DashboardAccesoriosIndexRoute
}

const DashboardAccesoriosRouteRouteChildren: DashboardAccesoriosRouteRouteChildren =
  {
    DashboardAccesoriosIndexRoute: DashboardAccesoriosIndexRoute,
  }

const DashboardAccesoriosRouteRouteWithChildren =
  DashboardAccesoriosRouteRoute._addFileChildren(
    DashboardAccesoriosRouteRouteChildren,
  )

interface DashboardActivosRouteRouteChildren {
  DashboardActivosConsultaDocumentosRoute: typeof DashboardActivosConsultaDocumentosRoute
  DashboardActivosNuevoRoute: typeof DashboardActivosNuevoRoute
  DashboardActivosIndexRoute: typeof DashboardActivosIndexRoute
  DashboardActivosActivoIdEditarRoute: typeof DashboardActivosActivoIdEditarRoute
  DashboardActivosCatalogoActivoIdRoute: typeof DashboardActivosCatalogoActivoIdRoute
  DashboardActivosActivoIdIndexRoute: typeof DashboardActivosActivoIdIndexRoute
  DashboardActivosCatalogoIndexRoute: typeof DashboardActivosCatalogoIndexRoute
}

const DashboardActivosRouteRouteChildren: DashboardActivosRouteRouteChildren = {
  DashboardActivosConsultaDocumentosRoute:
    DashboardActivosConsultaDocumentosRoute,
  DashboardActivosNuevoRoute: DashboardActivosNuevoRoute,
  DashboardActivosIndexRoute: DashboardActivosIndexRoute,
  DashboardActivosActivoIdEditarRoute: DashboardActivosActivoIdEditarRoute,
  DashboardActivosCatalogoActivoIdRoute: DashboardActivosCatalogoActivoIdRoute,
  DashboardActivosActivoIdIndexRoute: DashboardActivosActivoIdIndexRoute,
  DashboardActivosCatalogoIndexRoute: DashboardActivosCatalogoIndexRoute,
}

const DashboardActivosRouteRouteWithChildren =
  DashboardActivosRouteRoute._addFileChildren(
    DashboardActivosRouteRouteChildren,
  )

interface DashboardCategoriasRouteRouteChildren {
  DashboardCategoriasIndexRoute: typeof DashboardCategoriasIndexRoute
}

const DashboardCategoriasRouteRouteChildren: DashboardCategoriasRouteRouteChildren =
  {
    DashboardCategoriasIndexRoute: DashboardCategoriasIndexRoute,
  }

const DashboardCategoriasRouteRouteWithChildren =
  DashboardCategoriasRouteRoute._addFileChildren(
    DashboardCategoriasRouteRouteChildren,
  )

interface DashboardInventariosCategoriasRouteRouteChildren {
  DashboardInventariosCategoriasIndexRoute: typeof DashboardInventariosCategoriasIndexRoute
}

const DashboardInventariosCategoriasRouteRouteChildren: DashboardInventariosCategoriasRouteRouteChildren =
  {
    DashboardInventariosCategoriasIndexRoute:
      DashboardInventariosCategoriasIndexRoute,
  }

const DashboardInventariosCategoriasRouteRouteWithChildren =
  DashboardInventariosCategoriasRouteRoute._addFileChildren(
    DashboardInventariosCategoriasRouteRouteChildren,
  )

interface DashboardInventariosTiposInsumoTipoInsumoIdRouteRouteChildren {
  DashboardInventariosTiposInsumoTipoInsumoIdAtributosRoute: typeof DashboardInventariosTiposInsumoTipoInsumoIdAtributosRoute
  DashboardInventariosTiposInsumoTipoInsumoIdIndexRoute: typeof DashboardInventariosTiposInsumoTipoInsumoIdIndexRoute
}

const DashboardInventariosTiposInsumoTipoInsumoIdRouteRouteChildren: DashboardInventariosTiposInsumoTipoInsumoIdRouteRouteChildren =
  {
    DashboardInventariosTiposInsumoTipoInsumoIdAtributosRoute:
      DashboardInventariosTiposInsumoTipoInsumoIdAtributosRoute,
    DashboardInventariosTiposInsumoTipoInsumoIdIndexRoute:
      DashboardInventariosTiposInsumoTipoInsumoIdIndexRoute,
  }

const DashboardInventariosTiposInsumoTipoInsumoIdRouteRouteWithChildren =
  DashboardInventariosTiposInsumoTipoInsumoIdRouteRoute._addFileChildren(
    DashboardInventariosTiposInsumoTipoInsumoIdRouteRouteChildren,
  )

interface DashboardInventariosTiposInsumoRouteRouteChildren {
  DashboardInventariosTiposInsumoTipoInsumoIdRouteRoute: typeof DashboardInventariosTiposInsumoTipoInsumoIdRouteRouteWithChildren
  DashboardInventariosTiposInsumoIndexRoute: typeof DashboardInventariosTiposInsumoIndexRoute
}

const DashboardInventariosTiposInsumoRouteRouteChildren: DashboardInventariosTiposInsumoRouteRouteChildren =
  {
    DashboardInventariosTiposInsumoTipoInsumoIdRouteRoute:
      DashboardInventariosTiposInsumoTipoInsumoIdRouteRouteWithChildren,
    DashboardInventariosTiposInsumoIndexRoute:
      DashboardInventariosTiposInsumoIndexRoute,
  }

const DashboardInventariosTiposInsumoRouteRouteWithChildren =
  DashboardInventariosTiposInsumoRouteRoute._addFileChildren(
    DashboardInventariosTiposInsumoRouteRouteChildren,
  )

interface DashboardInventariosRouteRouteChildren {
  DashboardInventariosCategoriasRouteRoute: typeof DashboardInventariosCategoriasRouteRouteWithChildren
  DashboardInventariosTiposInsumoRouteRoute: typeof DashboardInventariosTiposInsumoRouteRouteWithChildren
  DashboardInventariosNuevoRoute: typeof DashboardInventariosNuevoRoute
  DashboardInventariosIndexRoute: typeof DashboardInventariosIndexRoute
  DashboardInventariosInsumoIdEditarRoute: typeof DashboardInventariosInsumoIdEditarRoute
}

const DashboardInventariosRouteRouteChildren: DashboardInventariosRouteRouteChildren =
  {
    DashboardInventariosCategoriasRouteRoute:
      DashboardInventariosCategoriasRouteRouteWithChildren,
    DashboardInventariosTiposInsumoRouteRoute:
      DashboardInventariosTiposInsumoRouteRouteWithChildren,
    DashboardInventariosNuevoRoute: DashboardInventariosNuevoRoute,
    DashboardInventariosIndexRoute: DashboardInventariosIndexRoute,
    DashboardInventariosInsumoIdEditarRoute:
      DashboardInventariosInsumoIdEditarRoute,
  }

const DashboardInventariosRouteRouteWithChildren =
  DashboardInventariosRouteRoute._addFileChildren(
    DashboardInventariosRouteRouteChildren,
  )

interface DashboardMantenimientosActividadesRouteRouteChildren {
  DashboardMantenimientosActividadesIndexRoute: typeof DashboardMantenimientosActividadesIndexRoute
}

const DashboardMantenimientosActividadesRouteRouteChildren: DashboardMantenimientosActividadesRouteRouteChildren =
  {
    DashboardMantenimientosActividadesIndexRoute:
      DashboardMantenimientosActividadesIndexRoute,
  }

const DashboardMantenimientosActividadesRouteRouteWithChildren =
  DashboardMantenimientosActividadesRouteRoute._addFileChildren(
    DashboardMantenimientosActividadesRouteRouteChildren,
  )

interface DashboardMantenimientosChecklistsRouteRouteChildren {
  DashboardMantenimientosChecklistsIndexRoute: typeof DashboardMantenimientosChecklistsIndexRoute
}

const DashboardMantenimientosChecklistsRouteRouteChildren: DashboardMantenimientosChecklistsRouteRouteChildren =
  {
    DashboardMantenimientosChecklistsIndexRoute:
      DashboardMantenimientosChecklistsIndexRoute,
  }

const DashboardMantenimientosChecklistsRouteRouteWithChildren =
  DashboardMantenimientosChecklistsRouteRoute._addFileChildren(
    DashboardMantenimientosChecklistsRouteRouteChildren,
  )

interface DashboardMantenimientosPrioridadesRouteRouteChildren {
  DashboardMantenimientosPrioridadesIndexRoute: typeof DashboardMantenimientosPrioridadesIndexRoute
}

const DashboardMantenimientosPrioridadesRouteRouteChildren: DashboardMantenimientosPrioridadesRouteRouteChildren =
  {
    DashboardMantenimientosPrioridadesIndexRoute:
      DashboardMantenimientosPrioridadesIndexRoute,
  }

const DashboardMantenimientosPrioridadesRouteRouteWithChildren =
  DashboardMantenimientosPrioridadesRouteRoute._addFileChildren(
    DashboardMantenimientosPrioridadesRouteRouteChildren,
  )

interface DashboardMantenimientosSolicitudesRouteRouteChildren {
  DashboardMantenimientosSolicitudesIndexRoute: typeof DashboardMantenimientosSolicitudesIndexRoute
}

const DashboardMantenimientosSolicitudesRouteRouteChildren: DashboardMantenimientosSolicitudesRouteRouteChildren =
  {
    DashboardMantenimientosSolicitudesIndexRoute:
      DashboardMantenimientosSolicitudesIndexRoute,
  }

const DashboardMantenimientosSolicitudesRouteRouteWithChildren =
  DashboardMantenimientosSolicitudesRouteRoute._addFileChildren(
    DashboardMantenimientosSolicitudesRouteRouteChildren,
  )

interface DashboardMantenimientosTiposMantenimientoRouteRouteChildren {
  DashboardMantenimientosTiposMantenimientoIndexRoute: typeof DashboardMantenimientosTiposMantenimientoIndexRoute
}

const DashboardMantenimientosTiposMantenimientoRouteRouteChildren: DashboardMantenimientosTiposMantenimientoRouteRouteChildren =
  {
    DashboardMantenimientosTiposMantenimientoIndexRoute:
      DashboardMantenimientosTiposMantenimientoIndexRoute,
  }

const DashboardMantenimientosTiposMantenimientoRouteRouteWithChildren =
  DashboardMantenimientosTiposMantenimientoRouteRoute._addFileChildren(
    DashboardMantenimientosTiposMantenimientoRouteRouteChildren,
  )

interface DashboardMantenimientosRouteRouteChildren {
  DashboardMantenimientosActividadesRouteRoute: typeof DashboardMantenimientosActividadesRouteRouteWithChildren
  DashboardMantenimientosChecklistsRouteRoute: typeof DashboardMantenimientosChecklistsRouteRouteWithChildren
  DashboardMantenimientosPrioridadesRouteRoute: typeof DashboardMantenimientosPrioridadesRouteRouteWithChildren
  DashboardMantenimientosSolicitudesRouteRoute: typeof DashboardMantenimientosSolicitudesRouteRouteWithChildren
  DashboardMantenimientosTiposMantenimientoRouteRoute: typeof DashboardMantenimientosTiposMantenimientoRouteRouteWithChildren
  DashboardMantenimientosIndexRoute: typeof DashboardMantenimientosIndexRoute
}

const DashboardMantenimientosRouteRouteChildren: DashboardMantenimientosRouteRouteChildren =
  {
    DashboardMantenimientosActividadesRouteRoute:
      DashboardMantenimientosActividadesRouteRouteWithChildren,
    DashboardMantenimientosChecklistsRouteRoute:
      DashboardMantenimientosChecklistsRouteRouteWithChildren,
    DashboardMantenimientosPrioridadesRouteRoute:
      DashboardMantenimientosPrioridadesRouteRouteWithChildren,
    DashboardMantenimientosSolicitudesRouteRoute:
      DashboardMantenimientosSolicitudesRouteRouteWithChildren,
    DashboardMantenimientosTiposMantenimientoRouteRoute:
      DashboardMantenimientosTiposMantenimientoRouteRouteWithChildren,
    DashboardMantenimientosIndexRoute: DashboardMantenimientosIndexRoute,
  }

const DashboardMantenimientosRouteRouteWithChildren =
  DashboardMantenimientosRouteRoute._addFileChildren(
    DashboardMantenimientosRouteRouteChildren,
  )

interface DashboardOrganizacionRouteRouteChildren {
  DashboardOrganizacionIndexRoute: typeof DashboardOrganizacionIndexRoute
  DashboardOrganizacionAreasIndexRoute: typeof DashboardOrganizacionAreasIndexRoute
  DashboardOrganizacionCargosIndexRoute: typeof DashboardOrganizacionCargosIndexRoute
  DashboardOrganizacionEmpleadosIndexRoute: typeof DashboardOrganizacionEmpleadosIndexRoute
  DashboardOrganizacionMigracionesIndexRoute: typeof DashboardOrganizacionMigracionesIndexRoute
  DashboardOrganizacionPersonasIndexRoute: typeof DashboardOrganizacionPersonasIndexRoute
}

const DashboardOrganizacionRouteRouteChildren: DashboardOrganizacionRouteRouteChildren =
  {
    DashboardOrganizacionIndexRoute: DashboardOrganizacionIndexRoute,
    DashboardOrganizacionAreasIndexRoute: DashboardOrganizacionAreasIndexRoute,
    DashboardOrganizacionCargosIndexRoute:
      DashboardOrganizacionCargosIndexRoute,
    DashboardOrganizacionEmpleadosIndexRoute:
      DashboardOrganizacionEmpleadosIndexRoute,
    DashboardOrganizacionMigracionesIndexRoute:
      DashboardOrganizacionMigracionesIndexRoute,
    DashboardOrganizacionPersonasIndexRoute:
      DashboardOrganizacionPersonasIndexRoute,
  }

const DashboardOrganizacionRouteRouteWithChildren =
  DashboardOrganizacionRouteRoute._addFileChildren(
    DashboardOrganizacionRouteRouteChildren,
  )

interface DashboardParametrosRouteRouteChildren {
  DashboardParametrosCatalogosRoute: typeof DashboardParametrosCatalogosRoute
  DashboardParametrosGestionRoute: typeof DashboardParametrosGestionRoute
  DashboardParametrosTiposDatoRoute: typeof DashboardParametrosTiposDatoRoute
  DashboardParametrosUbicacionesRoute: typeof DashboardParametrosUbicacionesRoute
  DashboardParametrosUnidadesMedidaRoute: typeof DashboardParametrosUnidadesMedidaRoute
}

const DashboardParametrosRouteRouteChildren: DashboardParametrosRouteRouteChildren =
  {
    DashboardParametrosCatalogosRoute: DashboardParametrosCatalogosRoute,
    DashboardParametrosGestionRoute: DashboardParametrosGestionRoute,
    DashboardParametrosTiposDatoRoute: DashboardParametrosTiposDatoRoute,
    DashboardParametrosUbicacionesRoute: DashboardParametrosUbicacionesRoute,
    DashboardParametrosUnidadesMedidaRoute:
      DashboardParametrosUnidadesMedidaRoute,
  }

const DashboardParametrosRouteRouteWithChildren =
  DashboardParametrosRouteRoute._addFileChildren(
    DashboardParametrosRouteRouteChildren,
  )

interface DashboardTiposActivoTipoActivoIdRouteRouteChildren {
  DashboardTiposActivoTipoActivoIdAtributosRoute: typeof DashboardTiposActivoTipoActivoIdAtributosRoute
  DashboardTiposActivoTipoActivoIdComponentesRoute: typeof DashboardTiposActivoTipoActivoIdComponentesRoute
  DashboardTiposActivoTipoActivoIdIndexRoute: typeof DashboardTiposActivoTipoActivoIdIndexRoute
}

const DashboardTiposActivoTipoActivoIdRouteRouteChildren: DashboardTiposActivoTipoActivoIdRouteRouteChildren =
  {
    DashboardTiposActivoTipoActivoIdAtributosRoute:
      DashboardTiposActivoTipoActivoIdAtributosRoute,
    DashboardTiposActivoTipoActivoIdComponentesRoute:
      DashboardTiposActivoTipoActivoIdComponentesRoute,
    DashboardTiposActivoTipoActivoIdIndexRoute:
      DashboardTiposActivoTipoActivoIdIndexRoute,
  }

const DashboardTiposActivoTipoActivoIdRouteRouteWithChildren =
  DashboardTiposActivoTipoActivoIdRouteRoute._addFileChildren(
    DashboardTiposActivoTipoActivoIdRouteRouteChildren,
  )

interface DashboardTiposActivoRouteRouteChildren {
  DashboardTiposActivoTipoActivoIdRouteRoute: typeof DashboardTiposActivoTipoActivoIdRouteRouteWithChildren
  DashboardTiposActivoHistorialRoute: typeof DashboardTiposActivoHistorialRoute
  DashboardTiposActivoIndexRoute: typeof DashboardTiposActivoIndexRoute
}

const DashboardTiposActivoRouteRouteChildren: DashboardTiposActivoRouteRouteChildren =
  {
    DashboardTiposActivoTipoActivoIdRouteRoute:
      DashboardTiposActivoTipoActivoIdRouteRouteWithChildren,
    DashboardTiposActivoHistorialRoute: DashboardTiposActivoHistorialRoute,
    DashboardTiposActivoIndexRoute: DashboardTiposActivoIndexRoute,
  }

const DashboardTiposActivoRouteRouteWithChildren =
  DashboardTiposActivoRouteRoute._addFileChildren(
    DashboardTiposActivoRouteRouteChildren,
  )

interface DashboardTiposDocumentoRouteRouteChildren {
  DashboardTiposDocumentoIndexRoute: typeof DashboardTiposDocumentoIndexRoute
}

const DashboardTiposDocumentoRouteRouteChildren: DashboardTiposDocumentoRouteRouteChildren =
  {
    DashboardTiposDocumentoIndexRoute: DashboardTiposDocumentoIndexRoute,
  }

const DashboardTiposDocumentoRouteRouteWithChildren =
  DashboardTiposDocumentoRouteRoute._addFileChildren(
    DashboardTiposDocumentoRouteRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardAccesoriosRouteRoute: typeof DashboardAccesoriosRouteRouteWithChildren
  DashboardActivosRouteRoute: typeof DashboardActivosRouteRouteWithChildren
  DashboardCategoriasRouteRoute: typeof DashboardCategoriasRouteRouteWithChildren
  DashboardInventariosRouteRoute: typeof DashboardInventariosRouteRouteWithChildren
  DashboardMantenimientosRouteRoute: typeof DashboardMantenimientosRouteRouteWithChildren
  DashboardOrganizacionRouteRoute: typeof DashboardOrganizacionRouteRouteWithChildren
  DashboardParametrosRouteRoute: typeof DashboardParametrosRouteRouteWithChildren
  DashboardTiposActivoRouteRoute: typeof DashboardTiposActivoRouteRouteWithChildren
  DashboardTiposDocumentoRouteRoute: typeof DashboardTiposDocumentoRouteRouteWithChildren
  DashboardPerfilRoute: typeof DashboardPerfilRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAccesoriosRouteRoute: DashboardAccesoriosRouteRouteWithChildren,
  DashboardActivosRouteRoute: DashboardActivosRouteRouteWithChildren,
  DashboardCategoriasRouteRoute: DashboardCategoriasRouteRouteWithChildren,
  DashboardInventariosRouteRoute: DashboardInventariosRouteRouteWithChildren,
  DashboardMantenimientosRouteRoute:
    DashboardMantenimientosRouteRouteWithChildren,
  DashboardOrganizacionRouteRoute: DashboardOrganizacionRouteRouteWithChildren,
  DashboardParametrosRouteRoute: DashboardParametrosRouteRouteWithChildren,
  DashboardTiposActivoRouteRoute: DashboardTiposActivoRouteRouteWithChildren,
  DashboardTiposDocumentoRouteRoute:
    DashboardTiposDocumentoRouteRouteWithChildren,
  DashboardPerfilRoute: DashboardPerfilRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
